WellMarkedStudents(StudentId, CourseId) :-
    Marks(StudentId, CourseId, Mark),
    Mark > 2.
CourseStudents(StudentId, CourseId) :-
    Students(StudentId, _, GroupId),
    Plan(GroupId, CourseId, _).
Debtors(StudentName, CourseName) :-
    Students(StudentId, StudentName, _),
    Courses(CourseId, CourseName),
    CourseStudents(StudentId, CourseId),
    not WellMarkedStudents(StudentId, CourseId).
