MarkedStudents(StudentId) :-
    Marks(StudentId, CourseId, _),
    Courses(CourseId, CourseName),
    CourseName = :CourseName.
CourseGroups(GroupId) :-
    Plan(GroupId, CourseId, _),
    Courses(CourseId, CourseName),
    CourseName = :CourseName.
StudentInformations(StudentId, StudentName, GroupName) :-
    Students(StudentId, StudentName, GroupId),
    Groups(GroupId, GroupName),
    not MarkedStudents(StudentId),
    CourseGroups(GroupId).
