MarkedStudent(StudentId, CourseId) :-
    Marks(StudentId, CourseId, _).
LecturerCourses(CourseId) :-
    Plan(_, CourseId, LecturerId),
    Lecturers(LecturerId, LecturerName),
    LecturerName = :LecturerName.
NotMarkedLecturerStudents(StudentId) :-
    Students(StudentId, _, _),
    LecturerCourses(CourseId),
    not MarkedStudent(StudentId, CourseId).
MarkedLecturerStudents(StudentId) :-
    Students(StudentId, _, _),
    not NotMarkedLecturerStudents(StudentId).
